"""add subjects to employee_applications

Revision ID: 2837b2b16781
Revises: cc36c61957c5
Create Date: 2026-02-22 12:28:55.301144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2837b2b16781'
down_revision: Union[str, Sequence[str], None] = 'cc36c61957c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_applications', sa.Column('subjects', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_applications', 'subjects')
    # ### end Alembic commands ###
