"""add classes to employee_applications

Revision ID: 2b892244d0af
Revises: 2837b2b16781
Create Date: 2026-02-27 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b892244d0af"
down_revision: Union[str, Sequence[str], None] = "2837b2b16781"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee_applications", sa.Column("classes", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee_applications", "classes")
    # ### end Alembic commands ###
