"""Initial migration

Revision ID: 6e3ff7cd897f
Revises: 
Create Date: 2026-02-03 12:40:08.581849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e3ff7cd897f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cnic', sa.String(), nullable=False),
    sa.Column('position_applied_for', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('highest_qualification', sa.String(), nullable=False),
    sa.Column('experience_years', sa.String(), nullable=False),
    sa.Column('cv_url', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('current_organization', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('apply_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leadership_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_table('school_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_registration_open', sa.Boolean(), nullable=True),
    sa.Column('application_deadlines', sa.JSON(), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regId', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('student_photo_url', sa.String(), nullable=True),
    sa.Column('guardian_name', sa.String(), nullable=False),
    sa.Column('guardian_cnic', sa.String(), nullable=False),
    sa.Column('guardian_phone', sa.String(), nullable=False),
    sa.Column('guardian_email', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('applying_for_class', sa.String(), nullable=False),
    sa.Column('previous_school', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_applications_regId'), 'student_applications', ['regId'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('system_student_id', sa.String(), nullable=True),
    sa.Column('admission_number', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('guardian_name', sa.String(), nullable=True),
    sa.Column('guardian_cnic', sa.String(), nullable=True),
    sa.Column('guardian_phone', sa.String(), nullable=True),
    sa.Column('guardian_email', sa.String(), nullable=True),
    sa.Column('b_form_number', sa.String(), nullable=True),
    sa.Column('student_cnic', sa.String(), nullable=True),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('student_photo_url', sa.String(), nullable=True),
    sa.Column('employee_type', sa.String(), nullable=True),
    sa.Column('functional_role', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('experience_years', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('cv_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_admission_number'), 'users', ['admission_number'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_system_student_id'), 'users', ['system_student_id'], unique=True)
    op.create_table('job_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['job_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_positions')
    op.drop_index(op.f('ix_users_system_student_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_admission_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_student_applications_regId'), table_name='student_applications')
    op.drop_table('student_applications')
    op.drop_table('school_configs')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_table('leadership_members')
    op.drop_table('job_categories')
    op.drop_table('employee_applications')
    # ### end Alembic commands ###
