"""Refactor models: separate students and employees, update applications and config

Revision ID: 7608f734435a
Revises: 77b8e388b47b
Create Date: 2026-02-03 14:57:04.054285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7608f734435a'
down_revision: Union[str, Sequence[str], None] = '77b8e388b47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrolled_employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cnic', sa.String(), nullable=False),
    sa.Column('employee_type', sa.String(), nullable=False),
    sa.Column('functional_role', sa.String(), nullable=False),
    sa.Column('system_role', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('highest_qualification', sa.Text(), nullable=False),
    sa.Column('experience_years', sa.String(), nullable=False),
    sa.Column('current_organization', sa.Text(), nullable=True),
    sa.Column('cv_url', sa.String(), nullable=True),
    sa.Column('lms_email', sa.String(), nullable=False),
    sa.Column('lms_login', sa.String(), nullable=False),
    sa.Column('lms_password', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('lms_email'),
    sa.UniqueConstraint('lms_login')
    )
    op.create_table('enrolled_students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reg_id', sa.String(), nullable=True),
    sa.Column('system_student_id', sa.String(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('student_photo_url', sa.String(), nullable=True),
    sa.Column('b_form_number', sa.String(), nullable=False),
    sa.Column('student_cnic', sa.String(), nullable=True),
    sa.Column('guardian_name', sa.String(), nullable=False),
    sa.Column('guardian_cnic', sa.String(), nullable=False),
    sa.Column('guardian_phone', sa.String(), nullable=False),
    sa.Column('guardian_email', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('applying_for_class', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lms_email', sa.String(), nullable=False),
    sa.Column('lms_login', sa.String(), nullable=False),
    sa.Column('lms_password', sa.String(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number'),
    sa.UniqueConstraint('lms_email'),
    sa.UniqueConstraint('lms_login'),
    sa.UniqueConstraint('reg_id'),
    sa.UniqueConstraint('system_student_id')
    )
    op.create_table('fee_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('challan_number', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['student_applications.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['enrolled_students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challan_number')
    )
    op.drop_index(op.f('ix_users_admission_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_system_student_id'), table_name='users')
    op.drop_table('users')
    op.alter_column('employee_applications', 'highest_qualification',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('employee_applications', 'cv_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_applications', 'current_organization',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('school_configs', sa.Column('school_name', sa.String(), nullable=False))
    op.add_column('school_configs', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('school_configs', sa.Column('interview_location', sa.String(), nullable=True))
    op.add_column('school_configs', sa.Column('interview_time_range', sa.String(), nullable=True))
    op.add_column('school_configs', sa.Column('challan_due_days', sa.Integer(), nullable=True))
    op.add_column('school_configs', sa.Column('admission_fee', sa.Integer(), nullable=True))
    op.add_column('school_configs', sa.Column('tuition_fee_base', sa.Integer(), nullable=True))
    op.add_column('school_configs', sa.Column('google_form_link', sa.String(), nullable=True))
    op.alter_column('student_applications', 'regId',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student_applications', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_applications', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('student_applications', 'regId',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('school_configs', 'google_form_link')
    op.drop_column('school_configs', 'tuition_fee_base')
    op.drop_column('school_configs', 'admission_fee')
    op.drop_column('school_configs', 'challan_due_days')
    op.drop_column('school_configs', 'interview_time_range')
    op.drop_column('school_configs', 'interview_location')
    op.drop_column('school_configs', 'logo_url')
    op.drop_column('school_configs', 'school_name')
    op.alter_column('employee_applications', 'current_organization',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('employee_applications', 'cv_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee_applications', 'highest_qualification',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('system_student_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admission_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('guardian_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('guardian_cnic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('guardian_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('guardian_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_form_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('student_cnic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('student_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('employee_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('functional_role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qualification', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('experience_years', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cv_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_system_student_id'), 'users', ['system_student_id'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_admission_number'), 'users', ['admission_number'], unique=True)
    op.drop_table('fee_payments')
    op.drop_table('enrolled_students')
    op.drop_table('enrolled_employees')
    # ### end Alembic commands ###
