"""Add pending_verification to StudentApplicationStatus

Revision ID: a11875da960c
Revises: aee7c12bd48c
Create Date: 2026-02-04 16:00:16.318257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a11875da960c"
down_revision: Union[str, Sequence[str], None] = "aee7c12bd48c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE studentapplicationstatus ADD VALUE 'pending_verification'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
