"""Initial complete schema

Revision ID: aee7c12bd48c
Revises: 7608f734435a
Create Date: 2026-02-04 15:36:49.598534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aee7c12bd48c"
down_revision: Union[str, Sequence[str], None] = "7608f734435a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Manual Enum creation
    op.execute(
        "CREATE TYPE employeeapplicationstatus AS ENUM ('applied', 'shortlisted', 'interviewed', 'hired', 'rejected')"
    )
    op.execute(
        "CREATE TYPE studentapplicationstatus AS ENUM ('applied', 'reviewed', 'accepted', 'rejected')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "contact_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exam_terms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subjects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "teacher", "staff", "student", name="userrole"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("receiver_id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column(
            "sent_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "class_subjects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["enrolled_employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salary_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("payment_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "paid", "verified", "rejected", name="paymentstatus"),
            nullable=True,
        ),
        sa.Column("month_year", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["enrolled_employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("class_subject_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["class_subject_id"],
            ["class_subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attendance_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("class_subject_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("present", "absent", "late", "excused", name="attendancestatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["class_subject_id"],
            ["class_subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["enrolled_students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lectures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("class_subject_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content_url", sa.String(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_subject_id"],
            ["class_subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exam_term_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("class_subject_id", sa.UUID(), nullable=False),
        sa.Column("total_marks", sa.Float(), nullable=False),
        sa.Column("obtained_marks", sa.Float(), nullable=False),
        sa.Column("grade", sa.String(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_subject_id"],
            ["class_subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_term_id"],
            ["exam_terms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["enrolled_students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "employee_applications",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "applied",
            "shortlisted",
            "interviewed",
            "hired",
            "rejected",
            name="employeeapplicationstatus",
        ),
        existing_nullable=True,
        postgresql_using="status::employeeapplicationstatus",
    )
    op.add_column("enrolled_employees", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "enrolled_employees", "users", ["user_id"], ["id"])

    # Delete incompatible data
    op.execute("DELETE FROM enrolled_students")

    op.add_column("enrolled_students", sa.Column("user_id", sa.UUID(), nullable=True))
    op.alter_column(
        "enrolled_students",
        "class_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="class_id::uuid",
    )
    op.alter_column(
        "enrolled_students",
        "section_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="section_id::uuid",
    )
    op.create_foreign_key(None, "enrolled_students", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "enrolled_students", "sections", ["section_id"], ["id"])
    op.create_foreign_key(None, "enrolled_students", "classes", ["class_id"], ["id"])
    op.alter_column(
        "fee_payments",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("pending", "paid", "verified", "rejected", name="paymentstatus"),
        existing_nullable=True,
        postgresql_using="status::paymentstatus",
    )
    op.alter_column(
        "student_applications",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "applied",
            "reviewed",
            "accepted",
            "rejected",
            name="studentapplicationstatus",
        ),
        existing_nullable=True,
        postgresql_using="status::studentapplicationstatus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "student_applications",
        "status",
        existing_type=sa.Enum(
            "applied",
            "reviewed",
            "accepted",
            "rejected",
            name="studentapplicationstatus",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "fee_payments",
        "status",
        existing_type=sa.Enum(
            "pending", "paid", "verified", "rejected", name="paymentstatus"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "enrolled_students", type_="foreignkey")
    op.drop_constraint(None, "enrolled_students", type_="foreignkey")
    op.drop_constraint(None, "enrolled_students", type_="foreignkey")
    op.alter_column(
        "enrolled_students",
        "section_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "enrolled_students",
        "class_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("enrolled_students", "user_id")
    op.drop_constraint(None, "enrolled_employees", type_="foreignkey")
    op.drop_column("enrolled_employees", "user_id")
    op.alter_column(
        "employee_applications",
        "status",
        existing_type=sa.Enum(
            "applied",
            "shortlisted",
            "interviewed",
            "hired",
            "rejected",
            name="employeeapplicationstatus",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_table("results")
    op.drop_table("lectures")
    op.drop_table("attendance_records")
    op.drop_table("assignments")
    op.drop_table("salary_records")
    op.drop_table("class_subjects")
    op.drop_table("sections")
    op.drop_table("messages")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("subjects")
    op.drop_table("exam_terms")
    op.drop_table("contact_messages")
    op.drop_table("classes")
    # ### end Alembic commands ###
