"""enhance_timetable_add_constraints_and_slots

Revision ID: b5a01fb7de90
Revises: ddec461c463a
Create Date: 2026-02-23 18:51:56.978815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5a01fb7de90'
down_revision: Union[str, Sequence[str], None] = 'ddec461c463a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_constraints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('max_periods_per_day', sa.Integer(), nullable=True),
    sa.Column('max_periods_per_week', sa.Integer(), nullable=True),
    sa.Column('unavailable_slots', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['enrolled_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_constraints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_subject_id', sa.UUID(), nullable=False),
    sa.Column('is_lab', sa.Boolean(), nullable=True),
    sa.Column('requires_double_period', sa.Boolean(), nullable=True),
    sa.Column('is_core', sa.Boolean(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_subject_id')
    )
    op.add_column('rooms', sa.Column('room_type', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('is_lab', sa.Boolean(), nullable=True))
    # Add periods_per_day as nullable first, set a safe default, then make NOT NULL
    op.add_column('timetable_configs', sa.Column('periods_per_day', sa.Integer(), nullable=True))
    op.execute("UPDATE timetable_configs SET periods_per_day = 6 WHERE periods_per_day IS NULL")
    op.alter_column('timetable_configs', 'periods_per_day', nullable=False)
    op.add_column('timetable_configs', sa.Column('break_details', sa.JSON(), nullable=True))
    op.add_column('timetable_configs', sa.Column('max_periods_per_teacher_day', sa.Integer(), nullable=True))
    op.add_column('timetable_configs', sa.Column('max_periods_per_teacher_week', sa.Integer(), nullable=True))
    op.drop_column('timetable_configs', 'break_periods')
    op.drop_column('timetable_configs', 'max_lectures_per_teacher')
    op.drop_column('timetable_configs', 'max_lectures_per_class')
    # Add period_index as nullable first, set default 0 for existing slots, then make NOT NULL
    op.add_column('timetable_slots', sa.Column('period_index', sa.Integer(), nullable=True))
    op.execute("UPDATE timetable_slots SET period_index = 0 WHERE period_index IS NULL")
    op.alter_column('timetable_slots', 'period_index', nullable=False)
    op.add_column('timetable_slots', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('timetable_slots', sa.Column('is_double_period', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable_slots', 'is_double_period')
    op.drop_column('timetable_slots', 'is_locked')
    op.drop_column('timetable_slots', 'period_index')
    op.add_column('timetable_configs', sa.Column('max_lectures_per_class', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timetable_configs', sa.Column('max_lectures_per_teacher', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timetable_configs', sa.Column('break_periods', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('timetable_configs', 'max_periods_per_teacher_week')
    op.drop_column('timetable_configs', 'max_periods_per_teacher_day')
    op.drop_column('timetable_configs', 'break_details')
    op.drop_column('timetable_configs', 'periods_per_day')
    op.drop_column('rooms', 'is_lab')
    op.drop_column('rooms', 'room_type')
    op.drop_table('subject_constraints')
    op.drop_table('teacher_constraints')
    # ### end Alembic commands ###
