"""add group_id to enrolled_students

Revision ID: cc36c61957c5
Revises: add_grp_id
Create Date: 2026-02-22 12:20:21.596793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc36c61957c5'
down_revision: Union[str, Sequence[str], None] = 'add_grp_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrolled_students', sa.Column('group_id', sa.UUID(), sa.ForeignKey('academic_groups.id'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrolled_students', 'group_id')
    # ### end Alembic commands ###
