"""Add code and group to classes

Revision ID: ed77c5164280
Revises: a11875da960c
Create Date: 2026-02-05 17:04:39.311217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed77c5164280'
down_revision: Union[str, Sequence[str], None] = 'a11875da960c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('code', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('group', sa.String(), nullable=True))
    op.drop_constraint(op.f('classes_name_key'), 'classes', type_='unique')
    op.create_unique_constraint(None, 'classes', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='unique')
    op.create_unique_constraint(op.f('classes_name_key'), 'classes', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('classes', 'group')
    op.drop_column('classes', 'code')
    # ### end Alembic commands ###
